version: '3.8'

services:
  token-flight-service:
    build:
      context: ./token-flight-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - token-flight-service
    environment:
      - VITE_API_URL=http://token-flight-service:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped 